import type { Metadata } from "next";
import Sidebar from "../shared/components/Sidebar";

export const metadata: Metadata = {
  title: "Management",
  description: "Generated by create next app",
};

export default function ManagerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="main-content flex-grow h-screen flex">
      <Sidebar />
      {children}
    </div>
  );
}
